import Footer from "../componentes/Footer"
import NavBar from "../componentes/navBar/navBar"


export const metadata = {
  title: 'Mi seccion',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
  return (
    <html lang="es" >
      <body className="" >
        <main className="w-screen min-h-screen  relative">
          <NavBar/>
        {children}
        </main>
        <Footer/>
        </body>
    </html>
  )
}
