import NavBar from "../componentes/navBar/navBar"


export const metadata = {
  title: 'Mi seccion',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
  return (
    <html lang="es" >
      <body >
        <main className="w-screen min-h-screen overflow-x-hidden relative">
          <NavBar/>
        {children}
        </main>
        
        </body>
    </html>
  )
}
